require("settings")
require("mappings")
require("packer-config")

require("colorschemes-config.rose-pine")
require("telescope-config")
require("nvim-tree-config")
require("harpoon-config")
require("undo-tree-config")
require("nvim-fugitive-config")
require("lsp-config")
require("astrojs-config")
